### PR TITLE
MAINT-39554 : fix space settings/members invite button position

### PR DESCRIPTION
**Pull request by Jihed525**
just as done in [PR](https://github.com/exoplatform/platform-ui/pull/106) by @hakermi , i have applied the same rules in space/settings/memebers on invite button

### CODE REVIEW

**Review by ahamdi — DISMISSED** [review]

**Comment by ahamdi** [comment]
@Jihed525 Is there a task for this issue ?

**Comment by Jihed525** [comment]
> @Jihed525 Is there a task for this issue ?

@ahamdi : it was reported in the same ticket after confirming the first fix, it would be sent as a patch, wdyt ?

**Comment by ahamdi** [comment]
Yes it will need another task , please create it !

**Review by ahamdi — APPROVED** [review]
@Jihed525 Please create a task for this PR

**Pull request merged**
