### PR TITLE
Maint-40750:Display hidden Space user invitation suggestion list

### PR DESCRIPTION
**Pull request by Jihed525**
In space Members Portlet users invitation field, When adding the first letters of user names, the suggestion list is hidden, thus, this fix would display this list

### CODE REVIEW

**Comment by ahamdi** [comment]
@Jihed525 @hakermi Could you check that this does not break the fix on MAINT-28527 ?

**Comment by Jihed525** [comment]
> @Jihed525 @hakermi Could you check that this does not break the fix on MAINT-28527 ?

@hakermi as far as I checked this didn't affect the fix in MAINT-28527, could you confirm ?

**Comment by hakermi** [comment]
> > @Jihed525 @hakermi Could you check that this does not break the fix on MAINT-28527 ?
> 
> @hakermi as far as I checked this didn't affect the fix in MAINT-28527, could you confirm ?

It's affect the fix, the size of the input text field will overflow the page size when writing a long text.

**Comment by Jihed525** [comment]
> > > @Jihed525 @hakermi Could you check that this does not break the fix on MAINT-28527 ?
> > 
> > 
> > @hakermi as far as I checked this didn't affect the fix in MAINT-28527, could you confirm ?
> 
> It's affect the fix, the size of the input text field will overflow the page size when writing a long text.

@hakermi This should be handled now, isn't it ?

**Review by hakermi — APPROVED** [review]
LGTM

**Pull request merged**
